---
title: ' On large and small data blow-up solutions in the Classical Trojan Y- Chromosome
  Model'
author: ' Eric Takyi'
date: []
slug: on-large-and-small-data-blow-up-solutions-in-the-classical-trojan-y-chromosome-model
categories: []
tags: []
event: Math/Stat Bio Seminar
subtitle: ''
summary: ''
authors: [Eric Takyi]
lastmod: '2020-02-26T15:10:40-06:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

**Abstract: **

The Trojan Y-Chromosome (TYC) strategy is a biological control used to cause the extinction of invasive fish populations by manipulating the populations sex ratio. This is done by introducing YY super males into the invasive population, which guarantees male progeny upon mating with the YY males. We consider a three species TYC model, and show that, if the introduction rate of trojan fish is zero, under certain large data assumptions, negative solutions are possible for the male population which can in turn lead to finite time blow-up in the female and male populations. In order to overcome this, we will propose models that possess globally existing non-negative solutions, in any parameter or initial data regime.