---
title: Why Multilingual, and How to Keep It -- An Evolutionary Dynamics Perspective
author: ''
date: []
slug: why-multilingual-and-how-to-keep-it-an-evolutionary-dynamics-perspective
categories: []
tags: []
subtitle: ''
summary: ''
event: Math/Stat Bio Seminar
authors: [Dr. Zhijun Wu]
lastmod: '2020-03-09T15:10:03-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---
**Abstract: **

While many languages are in danger of extinction worldwide, multilingualism is being adopted for communication among different language groups, and playing a unique role of preserving language and cultural diversities. How multilingualism is developed and maintained therefore becomes an important interdisciplinary research subject for understanding complex social changes of modern-day societies. Here we consider a mixed population of multilingual speakers, with multilingual defined broadly as zero, limited, or full uses of multiple languages or dialects, and propose an evolutionary dynamic model for its development and evolution. The model consists of two different parts, formulated as two different evolutionary games. The first part accounts for selection of languages based on competition for population and social or economic preferences. The second part relates to circumstances when selection of languages is altered, for better or worse, by forces other than competition such as public policies, education, or family influences. By combining competition with intervention, we show how multilingualism may evolve under these two different sources of influences. We show in particular that by choosing appropriate interventional strategies, stable co-existence of languages, especially in multilingual forms, is possible, and extinction can be prevented, which is in contrast with major predictions from previous studies that co-existence of languages is unstable in general, and one language will eventually dominate the population while all others extinct.